let lectureTextBuffer = '';

// Quick startup check to light up the UI badge
function bootCoreSystem() {
    const badge = document.getElementById('ai-system-badge');
    const runButton = document.getElementById('ai-btn');
    const commsStatus = document.getElementById('comms-status');
    
    badge.style.borderColor = '#22c55e';
    badge.style.background = '#1b5e20';
    badge.innerText = '✓ Local AI Engine Ready';
    runButton.disabled = false;
    commsStatus.innerText = 'Microphone status: Ready to record.';
}

// Fallback check for Safari/Firefox compatibility 
const SpeechFramework = window.SpeechRecognition || window.webkitSpeechRecognition;
if (!SpeechFramework) {
    alert("Voice recognition is not supported in this browser window. Please use Google Chrome or Edge.");
}

const transcriptionEngine = new SpeechFramework();
transcriptionEngine.continuous = true;
transcriptionEngine.interimResults = true;
transcriptionEngine.lang = 'en-US';

const startBtn = document.getElementById('start-btn');
const stopBtn = document.getElementById('stop-btn');
const transcriptView = document.getElementById('transcript');
const commsStatus = document.getElementById('comms-status');
const aiBtn = document.getElementById('ai-btn');
const aiOutput = document.getElementById('ai-output');
const copyBtn = document.getElementById('copy-btn');

transcriptionEngine.onstart = () => { commsStatus.innerText = "Microphone status: Listening..."; startBtn.disabled = true; stopBtn.disabled = false; };
transcriptionEngine.onend = () => { commsStatus.innerText = "Microphone status: Stopped."; startBtn.disabled = false; stopBtn.disabled = true; };
transcriptionEngine.onerror = (err) => { commsStatus.innerText = "Recording error: " + err.error; };

transcriptionEngine.onresult = (event) => {
    let runningInterimString = '';
    for (let i = event.resultIndex; i < event.results.length; ++i) {
        if (event.results[i] && event.results[i][0]) {
            if (event.results[i].isFinal) {
                lectureTextBuffer += event.results[i][0].transcript + ' ';
            } else {
                runningInterimString += event.results[i][0].transcript;
            }
        }
    }
    transcriptView.value = lectureTextBuffer + runningInterimString;
};

startBtn.addEventListener('click', () => { lectureTextBuffer = ''; transcriptView.value = ''; transcriptionEngine.start(); });
stopBtn.addEventListener('click', () => { transcriptionEngine.stop(); });

aiBtn.addEventListener('click', async () => {
    const rawBuffer = transcriptView.value.trim();
    if (!rawBuffer) return alert("Please Record Some Notes First");

    aiOutput.innerText = "Processing lecture text through local edge server arrays...";

    try {
        const response = await fetch("https://nomic.ai", {
            method: "POST",
            headers: { 
                "Content-Type": "application/json"
            },
            body: JSON.stringify({ 
                prompt: `### Instruction:\nSummarize this lecture transcript into a concise paragraph, then list the key points as bullets.\n\n### Input:\n${rawBuffer}\n\n### Response:\n`,
                max_tokens: 150,
                temperature: 0.3
            })
        });

        if (!response.ok) {
            throw new Error(`Server returned status code ${response.status}`);
        }

        const result = await response.json();
        
        let aiOutputText = "";
        if (result && result.choices && result.choices[0] && result.choices[0].text) {
            aiOutputText = result.choices[0].text.trim();
        } else {
            aiOutputText = JSON.stringify(result);
        }

        const cleanSentences = aiOutputText.match(/[^.!?]+[.!?]*/g) || [aiOutputText];
        let abstractParagraph = cleanSentences[0];
        let operationalBullets = cleanSentences.slice(1);

        if (operationalBullets.length === 0) {
            operationalBullets = [aiOutputText];
            abstractParagraph = "Core overview generated by AI summary engine.";
        }

        let layoutDOM = `
            <div class="section-header">📝 Lecture Summary:</div>
            <p style="margin: 0 0 16px 0; color: #d4d4d8;">${abstractParagraph.trim()}</p>
            <div class="section-header">🎯 Key Points & Takeaways:</div>
            <ul style="margin: 0; padding-left: 20px; color: #d4d4d8;">
        `;
        
        operationalBullets.forEach(sentence => {
            let cleanSentence = sentence.replace(/^[-*•\d.]+\s*/, "").trim();
            if (cleanSentence.length > 4) {
                cleanSentence = cleanSentence.charAt(0).toUpperCase() + cleanSentence.slice(1);
                layoutDOM += `<li style="margin-bottom: 6px;">${cleanSentence}</li>`;
            }
        });
        layoutDOM += `</ul>`;
        aiOutput.innerHTML = layoutDOM;

    } catch (err) {
        console.error(err);
        aiOutput.innerText = "Connection failed: " + err.message;
    }
});

copyBtn.addEventListener('click', () => {
    navigator.clipboard.writeText(aiOutput.innerText);
    const originalLabel = copyBtn.innerText;
    copyBtn.innerText = "Copied to clipboard!";
    setTimeout(() => copyBtn.innerText = originalLabel, 1500);
});

bootCoreSystem();